apiVersion: apps/v1
kind: Deployment
metadata:
  name: bmkg-rest-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bmkg-rest-service
  template:
    metadata:
      labels:
        app: bmkg-rest-service
    spec:
      containers:
        - name: bmkg-rest-service
          image: asia.gcr.io/archisdi-285415/bmkg-rest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bmkg-rest-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: bmkg-rest-service
  ports:
    - port: 8030
      targetPort: 8080
