// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	models "bmkg/models"

	mock "github.com/stretchr/testify/mock"
)

// EarthquakeServiceAPI is an autogenerated mock type for the EarthquakeServiceAPI type
type EarthquakeServiceAPI struct {
	mock.Mock
}

// RetrieveLastEarthquake provides a mock function with given fields:
func (_m *EarthquakeServiceAPI) RetrieveLastEarthquake() (models.Earthquake, error) {
	ret := _m.Called()

	var r0 models.Earthquake
	if rf, ok := ret.Get(0).(func() models.Earthquake); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.Earthquake)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RetrieveLatestEarthquakes provides a mock function with given fields:
func (_m *EarthquakeServiceAPI) RetrieveLatestEarthquakes() ([]models.Earthquake, error) {
	ret := _m.Called()

	var r0 []models.Earthquake
	if rf, ok := ret.Get(0).(func() []models.Earthquake); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Earthquake)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
