// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	models "bmkg/models"

	mock "github.com/stretchr/testify/mock"
)

// EarthquakeRepositoryApi is an autogenerated mock type for the EarthquakeRepositoryApi type
type EarthquakeRepositoryApi struct {
	mock.Mock
}

// GetLastEarthquake provides a mock function with given fields:
func (_m *EarthquakeRepositoryApi) GetLastEarthquake() (models.LastEartquake, error) {
	ret := _m.Called()

	var r0 models.LastEartquake
	if rf, ok := ret.Get(0).(func() models.LastEartquake); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.LastEartquake)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLatestEarthquake provides a mock function with given fields:
func (_m *EarthquakeRepositoryApi) GetLatestEarthquake() (models.LatestEarthquake, error) {
	ret := _m.Called()

	var r0 models.LatestEarthquake
	if rf, ok := ret.Get(0).(func() models.LatestEarthquake); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.LatestEarthquake)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
