// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	models "bmkg/models"

	mock "github.com/stretchr/testify/mock"
)

// WeatherServiceAPI is an autogenerated mock type for the WeatherServiceAPI type
type WeatherServiceAPI struct {
	mock.Mock
}

// RetrieveRegionalWeatherForecast provides a mock function with given fields: region, baseCoordinate
func (_m *WeatherServiceAPI) RetrieveRegionalWeatherForecast(region string, baseCoordinate string) (models.WeatherOutput, error) {
	ret := _m.Called(region, baseCoordinate)

	var r0 models.WeatherOutput
	if rf, ok := ret.Get(0).(func(string, string) models.WeatherOutput); ok {
		r0 = rf(region, baseCoordinate)
	} else {
		r0 = ret.Get(0).(models.WeatherOutput)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(region, baseCoordinate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
