// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	models "bmkg/models"

	mock "github.com/stretchr/testify/mock"
)

// WeatherRepositoryAPI is an autogenerated mock type for the WeatherRepositoryAPI type
type WeatherRepositoryAPI struct {
	mock.Mock
}

// GetWeatherForecast provides a mock function with given fields: location
func (_m *WeatherRepositoryAPI) GetWeatherForecast(location string) (models.BaseWeather, error) {
	ret := _m.Called(location)

	var r0 models.BaseWeather
	if rf, ok := ret.Get(0).(func(string) models.BaseWeather); ok {
		r0 = rf(location)
	} else {
		r0 = ret.Get(0).(models.BaseWeather)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(location)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
